### ISSUE TITLE
Add captions to images

### ISSUE THREAD

**Issue by bhavanakv** [yrahul3910/journal#27]
Add support for captions for images in entries, and search based on the caption.

**Comment by yrahul3910** [comment]
This is planned for the next stable release. The betas, however, will focus on the bug fixes.

**Comment by yrahul3910** [comment]
Possible implementations are modifying the `attachments` array to now be an array of objects, destroying backward compatibility, and adding a new `captions` array to the entry, with the caveat that care must be taken to make sure things are aligned right.

**Comment by yrahul3910** [comment]
@bhavanakv Because images are currently added simply via an `input` with multi-file selection enabled, choosing captions for individual images is less trivial. Please open two separate issues for this (one for adding captions, another for search based on captions), and I'll close this one.

**Comment by yrahul3910** [comment]
@bhavanakv I'm closing this issue in favor of two newer issues.
